language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
install:
  - pip install .
  - pip install git+https://github.com/rjbs/tapsimple
script: ( cd tests && python rx-test.py )
